version: '3.8'

services:
  u_jump:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: u_jump
    depends_on:
      - ollama
    networks:
      - ollama-docker
      - u_jump-docker


  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MAX_LOADED_MODELS=4
    networks:
      - ollama-docker
      - u_jump-docker
  
networks:
  ollama-docker:
    external: false
    name: ollama
  u_jump-docker:
    name: u_jump
